### ISSUE TITLE
Do you know of any Delphi wrappers for reaper-sdk?

### ISSUE THREAD

**Issue by War3Evo** [RuudErmers/ClapForDelphi#1]
Do you know of any Delphi wrappers for [reaper-sdk](https://github.com/justinfrankel/reaper-sdk) ??

Just curious.

**Comment by RuudErmers** [comment]
No, allthough that is interesting. In fact I created a large sdk project to send data from my Delphi application to that plugin to set parameters, volume settings and more in Reaper. But that project itself is written in C++ (with Visual Studio Community Edition), using this SDK. I am still doubting between that and using OSC which works great as well. (I also have a web api)
